<?php

namespace app\filterTool;

use pms\FilterTool\FilterTool;

/**
 * 修改文章状态的过滤工具
 * Class ArticleES
 * @package app\filterTool
 */
class ArticleES extends FilterTool
{
    protected function initialize()
    {
        $this->_Rules[] = ['id', 'int'];
        $this->_Rules[] = ['status', 'int'];
        parent::initialize(); // TODO: Change the autogenerated stub
    }


}