<?php

namespace app\filterTool;

use pms\FilterTool\FilterTool;

class CateFilter extends FilterTool
{

    protected function initialize()
    {
        $this->_Rules = [
            ['title', 'string'],
            ['name', 'string'],
            ['pid', 'int'],
            ['pid', 'int'],
            ['meta_title', 'string'],
            ['description', 'string'],
            ['allow_publish', 'int'],
            ['display', 'int'],
            ['check', 'int'],
        ];
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}