<?php

namespace app\filterTool;

use pms\FilterTool\FilterTool;

class CateFilter extends FilterTool
{

    protected function initialize()
    {
        $this->_Rules = [
            ['title' => 'string']
        ];
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}